# Generated by Django 4.0.3 on 2022-03-19 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('hr_name', models.CharField(max_length=250)),
                ('designation_hr', models.CharField(max_length=250)),
                ('contact', models.CharField(max_length=250)),
                ('board_no', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('designation', models.CharField(max_length=250)),
                ('contact', models.CharField(max_length=250)),
                ('duration_allowed', models.IntegerField()),
                ('allowed_from', models.DateField()),
                ('allowed_till', models.DateField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=250)),
                ('enrollment_no', models.CharField(max_length=250)),
                ('institute', models.CharField(max_length=250)),
                ('course', models.CharField(max_length=250)),
                ('branch', models.CharField(max_length=250)),
                ('sem', models.IntegerField()),
                ('year', models.IntegerField()),
                ('contact', models.CharField(max_length=250)),
                ('father_name', models.CharField(max_length=250)),
                ('father_contact', models.CharField(max_length=250)),
                ('signature', models.BooleanField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_1', models.IntegerField()),
                ('semester_2', models.IntegerField()),
                ('semester_3', models.IntegerField()),
                ('semester_4', models.IntegerField()),
                ('semester_5', models.IntegerField()),
                ('semester_6', models.IntegerField()),
                ('semester_7', models.IntegerField()),
                ('semester_8', models.IntegerField()),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.student')),
            ],
        ),
    ]
